trigger:
  - staging
  - trying
  - master
jobs:
  - job: Tox
    displayName: Tox
    strategy:
        matrix:
            Linux:
                vmImage: ubuntu-latest
    pool:
        vmImage: $(vmImage)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
      - script: sudo apt-get install -y --no-install-recommends openmpi-bin libopenmpi-dev
        displayName: Install openmpi
      - script: pip install -U tox
        displayName: Install tox
      - script: tox
        displayName: Run tox
